GET https://localhost:5001/api/genres
###
GET https://localhost:5001/api/games
###
GET https://localhost:5001/api/customers 
#почему роль ровна null ?

###
POST https://localhost:5001/api/users
Content-Type: application/json

{
    "name" : "Simulator"
}
###
GET https://localhost:5001/api/Users
###


 //Authorization

###
GET https://localhost:5001/api/genres
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlZsYWQiLCJyb2xlIjpbImFkbWluIiwiY3VzdG9tZXIiLCJtYW5hZ2VyIl0sIm5iZiI6MTU5MTU2MjU1MSwiZXhwIjoxNTkxNTYyODUxLCJpYXQiOjE1OTE1NjI1NTF9.RTrLndT4YJhKIYvo2GWHEjWvDALURZ8Ck711NAvevPI
###
POST localhost:5001/api/auth/authenticate
Content-Type: application/json

{
    "Login":"int123",
    "Password":"123456"
}

###
DELETE    https://localhost:5001/api/games/1
#Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlZsYWQiLCJyb2xlIjpbImFkbWluIiwiY3VzdG9tZXIiLCJtYW5hZ2VyIl0sIm5iZiI6MTU5MTU2MjY3NCwiZXhwIjoxNTkxNTYyOTc0LCJpYXQiOjE1OTE1NjI2NzR9.iL1jXwK5F3QRArJ7FAxpTR44dAdxxf9_sSMPqq8nhQQ


