GET https://localhost:5001/api/genres
###
GET https://localhost:5001/api/games
###
GET https://localhost:5001/api/customers 
###
 //Authorization
POST localhost:5001/api/auth/authenticate
Content-Type: application/json

{
    "Login":"LoveGame1",
    "Password":"000000"
}
###
DELETE https://localhost:5001/api/games/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik5pa2l0YSIsInJvbGUiOiJjdXN0b21lciIsIm5iZiI6MTU5MTYyODgwMiwiZXhwIjoxNTkxNjI5MTAyLCJpYXQiOjE1OTE2Mjg4MDJ9.xOi3FKOGC52Ery9SfxfwYelTx2e5mz58Q3tjQY8O0-U